<a href="https://colab.research.google.com/github/das2002/Remote-Sensing-Beaverworks/blob/master/01a_Intro_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to (/review of) python 
In the next few lessons, we'll review basic python and programming concepts, as well as go over the fundamentals of how to use some common python packages, such as:
- numpy
- pandas
- matplotlib

## Importing packages
Packages are collections of pre-written code made available for reuse. In the previous lesson, we installed some necessary packages using the `pip` python package manager. Packages are convenient because they save you from having to implement every feature and function on your own. The widely-used packages also provide a standard, common set of tools for others to develop with --- allowing interoperability between programs.

There are a few different ways to import  package in python:

The simplest is just to `import {packagename}`. For this lesson, we'll use `numpy` as the example package
```
import numpy
```
The functions, classes, and variables of the `numpy` package can then be accessed using "dot" notation: for example, the numpy array class can be accessed with `numpy.array`

---
A variant of this is to use `import {packagename} as {shortname}`, as in:
```
import numpy as np
```
This reduces the number of characters needed to type, and can be convenient if the package name is long, or you need to use many things from the same package. Accessing the numpy array class, for example, can be done with ```np.array```

---

If you only need a subset of items from a package, for example, a single class, function, or a submodule (subpackage of the main package), you can use the syntax ``` from {packagename} import {element}```, as in:
```
from numpy import array
```
This allows you to use the `array` class directly, without importing the rest of the numpy package, and without needing to use the package prefix dot notation.
For example, if you use this import method, then writing
```
test_array = array([0])
```
would be equivalent to writing
```
test_array = numpy.array([0])
test_array = np.array([0])
```
using the previous import styles, respectively.

In [0]:
import numpy as np

In [0]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


## Documentation

Packages contain functions, classes, and variables which may be helpful. Crucial to the usability of a package is the documentation (or API reference), which (should) list all of the contents of the package, and how to use them.

To get the built-in help about a function or class, use the `help()` command

Documentation for most common packages are also usually available online. For example, the documentation for [numpy can be found here](https://docs.scipy.org/doc/numpy/reference/)

In [0]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



### Commenting code
In order for your code to be readable to others (or your future self), you should provide comments on your code to explain what you are doing. The comment character in python is `#`, and any text following a `#` symbol will not be interpreted as code by python.

In [0]:
array_of_zeros = np.zeros([3,3]) # this creates a 3x3 array full of zeros
print(array_of_zeros) # the print() function displays the value of the variable on screen

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Code flow


### Loops
A key part of programming is automating repetitive tasks, such as applying the same operation to a list of inputs. This is achieved using "loops"; most commonly, the `for` loop.

In its simplest form, a python loop iterates over a list, and runs the code within the loop with the variable set equal to the respective element of the list.

In [0]:
idx_list = [0,1,2,3,4,5]
for idx in idx_list: # loop over idx_list, set idx equal to each element sequentially
  print('idx is equal to {}'.format(idx)) # print the current value of idx
  print(f'idx is equal to {idx}')
  print(idx)

idx is equal to 0
idx is equal to 0
0
idx is equal to 1
idx is equal to 1
1
idx is equal to 2
idx is equal to 2
2
idx is equal to 3
idx is equal to 3
3
idx is equal to 4
idx is equal to 4
4
idx is equal to 5
idx is equal to 5
5


Lists are not the only kinds of objects that can be iterated over (also known as an iterable). A special kind of object, called a generator, does not explicitly store every single value in memory, but instead stores the current value, and the rule to generate the next value. This can often be faster than explicitly storing every element.

As an analogy, if you wanted to send to your friend the following sequence of numbers: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59], you could write each number down and send them the entire list. Or you could write "the sequence of numbers starting at 1, increasing by 2, but less than 60"

If the sequence is very long, then the second representation becomes preferable to write, because you don't need to explicitly write out every single element. One common generator that is used in python is `range(start, end, increment)`, which creates a generator that produces the sequence of numbers starting at `start`, increments by `increment`, and is less than (__but not equal to__) `end`.  If `increment` is not set, it defaults to 1.

This is often used in conjunction with iteration:

In [0]:
for idx in range(0,6): #equivalent to the above
  print('idx is equal to {}'.format(idx)) # print the current value of idx

idx is equal to 0
idx is equal to 1
idx is equal to 2
idx is equal to 3
idx is equal to 4
idx is equal to 5


In [0]:
for idx in range(6): # if you only give one argument, it automatically starts from 0
  print('idx is currently {}'.format(idx)) # print the current value of idx

idx is currently 0
idx is currently 1
idx is currently 2
idx is currently 3
idx is currently 4
idx is currently 5


In [0]:
for idx in range(1,6, 2): #This is an example of the range(start,end,increment) 
  print('idx is equal to {}'.format(idx)) # print the current value of idx

idx is equal to 1
idx is equal to 3
idx is equal to 5


>for idx in range(0,60):

>> print(idx)


>for idx in range(0,600000):

>> print(idx)


would use the same amount of memory because they are generated but not stored







### Conditionals
Sometimes you want to execute code only if certain conditions are met. The `if`, `elif` (short for else-if), and `else` keywords are used for this purpose

In [0]:
for idx in range(1,6):
  if idx > 2 : # only execute the following indented block of code if idx is greater than 2
    print('idx={}, which is greater than 2'.format(idx))
  elif idx == 2: # only execute if the above condition isn't met, and also idx==2
  # note that == is used to check for equality; single = is the assignment operator
    print('idx={} is equal to 2'.format(idx)) 
  else: # execute this code if none of the above conditions are met
    print('idx={} is less than 2'.format(idx))

idx=1 is less than 2
idx=2 is equal to 2
idx=3, which is greater than 2
idx=4, which is greater than 2
idx=5, which is greater than 2


You can combine different conditions using the keywords `and` and `or`, and negate conditions using `not`

In [0]:
x = 5
y = 10
print(x==5 or y==11) # true because first statement is true
print(x==5 and y==11) # false because not both are true
print(x==5 and not y==11) # true because second condition is negated (flipped)

True
False
True


### List comprehension

You can generate a list from any iterable in a couple ways. This is called list comprehension.

The simplest way is just to call `list()` on the generator object

In [0]:
list(range(6))

[0, 1, 2, 3, 4, 5]

Another way is using the following syntax:

```
[x for x in iterable]
```
for example:

In [0]:
list_of_numbers = [x for x in range(6)]
print(list_of_numbers)

[0, 1, 2, 3, 4, 5]

However, the list comprehension syntax is actually more powerful than that: it allows for functions to be called within the expression
```
[expression(x) for x in iterable]
```

In [0]:
list_of_first_five_squares = [x**2 for x in range(6)] # the double star ** expression denotes exponentiation
# hence, the above gives the first 5 square numbers, including zero
print(list_of_first_five_squares)

[0, 1, 4, 9, 16, 25]

In fact, the list comprehension syntax is even more powerful: it can also include conditional statements
```
[expression(x) for x in iterable if condition]
```

In [0]:
list_of_first_few_odd_squares = [x**2 for x in range(10) if np.mod(x,2) == 1] 
print(list_of_first_few_odd_squares)

[1, 9, 25, 49, 81]


## Functions
Functions are a way to repeat the same lines of code, potentially with different inputs. If you find yourself writing a lot of repetitive code that shares the same structure, you may want to try and formulate it as a function. Functions are declared using the `def` keyword. In this example, we will write a function that checks if a number is prime.


In [0]:
def is_prime(number):
  if(number==1 or number==0):
    return False
  
  sqrt_num = int(np.sqrt(number)) # we only need to check integer factors up to the square root of the number, rounded down (int() always rounds down)
  for potential_factor in range(2,sqrt_num+1): #range(a,b) iterates from the value a to b-1
    if np.mod(number, potential_factor) == 0: #np.mod() is the modulo (aka remainder) function; thus, if the remainder is zero, then it divides evenly
      return False # if it divides evenly, then it's not prime, then we can return and end the function
  return True #if we get through all of the potential factors and haven't found a factor, then it's prime
  

In [0]:
is_prime(101.0)

True

## Data structures

### Lists
We already looked at one python data structure: the list. Lists are _ordered_ collections of values, denoted with square brackets. 

Lists are _ordered_ in the sense that the order of their elements matter. The list [1,2,3,4] is not the same as [4,3,2,1]

In [0]:
a_list = [2,0,15,5] # square brackets denote a list
another_list = [15,0,5,2]
print('a_list = {}; another_list = {}'.format(a_list, another_list)) # the .format() function of strings allows you to plug in the variable values in the respective curly braces {}

print('is a_list equal to another_list?')
print(a_list == another_list) # print out the truth value of whether a_list is the same as another_list (it shouldn't be, because they have different ordering)

yet_another_list = [2,0,15,5]
print('but it is equal to yet_another_list:')
print(a_list == yet_another_list)

a_list = [2, 0, 15, 5]; another_list = [15, 0, 5, 2]
is a_list equal to another_list?
False
but it is equal to yet_another_list
True


List elements can be any python object, including strings, numbers, and other lists

In [0]:
diverse_list = ['a', False, [0,0,0], 1.0, 10]
print('the elements of diverse_list are: {}'.format(diverse_list))
print('the data types of the elements are {}'.format([type(x) for x in diverse_list])) # using list comprehension to get the type of each element

the elements of diverse_list are: ['a', False, [0, 0, 0], 1.0, 10]
the data types of the elements are [<class 'str'>, <class 'bool'>, <class 'list'>, <class 'float'>, <class 'int'>]


You can access a specific element of a list using the square bracket notation (this is known as indexing)
```
list_name[idx]
```
Index values can be negative, which start counting from the end. So `list_name[-1]` gives the __last__ element of the list

In [0]:
first_element_of_diverse_list = diverse_list[0] # python starts counting at 0, so the first element is at index 0
print(first_element_of_diverse_list)
last_element_of_diverse_list = diverse_list[-1]
print(last_element_of_diverse_list)

a
10


You can "slice" a list using the colon `:` notation
```
list_name[start_idx:end_idx]
```
Note that the slice starts at the start_idx, but __does not include__ the element at end_idx.

If you omit either start_idx or end_idx, it automatically starts at the first element/ends at the last element respectively

In [0]:
print(diverse_list[0:2]) # gets the elements at index 0 and 1
print(diverse_list[:2]) # equivalent to the above
print(diverse_list[2:]) # gets all elements from index 2 to the end
print(diverse_list[:]) # gets all elements

['a', False]
['a', False]
[[0, 0, 0], 1.0, 10]
['a', False, [0, 0, 0], 1.0, 10]


Lists are modifiable: you can append and delete entries, as well as change the values of elements

In [0]:
diverse_list.append('new entry') # add a value to the end
print('appended an entry to diverse_list: {}'.format(diverse_list))
diverse_list[0] = 'changed entry' # change the value of entry at index 0
print('changed an entry of diverse_list: {}'.format(diverse_list))
first_entry = diverse_list.pop(0) # remove (and return) the value at element 0
print('removed "{}" from diverse_list: {}'.format(first_entry, diverse_list))
diverse_list.remove('new entry') # you can also remove the first entry with a specific value, in this case, the "new entry"
print('removed "new entry" from diverse_list: {}'.format(diverse_list))
diverse_list.insert(0,'a') # insert the value 'a' at index 0
print('inserted "a" back into diverse_list: {}'.format(diverse_list))

appended an entry to diverse_list: ['a', False, [0, 0, 0], 1.0, 10, 'new entry']
changed an entry of diverse_list: ['changed entry', False, [0, 0, 0], 1.0, 10, 'new entry']
removed "changed entry" from diverse_list: [False, [0, 0, 0], 1.0, 10, 'new entry']
removed "new entry" from diverse_list: [False, [0, 0, 0], 1.0, 10]
inserted "a" back into diverse_list: ['a', False, [0, 0, 0], 1.0, 10]


### Tuples
Tuples are unchangeable, ordered sequences of elements, grouped with regular parentheses:
```
('a','b','c')
```

In [0]:
a_tuple = ('a','b','c')
print('the first element of a_tuple is "{}"'.format(a_tuple[0])) # tuples can be indexed like lists

the first element of a_tuple is "a"


In [0]:
a_tuple[0] = 10 # however, unlike lists, you cannot change their values once they are set

TypeError: ignored

### Dictionaries
Dictionaries are data structures that store _mappings_ from "keys" to respective "values". You can think of them as lookup tables which return a specific value for a given key. For example, an english dictionary (the book) could be stored as a python dictionary, where the "keys" are each of the words in english, and the "values" are the respective definitions.

They are defined using the curly braces, or the `dict()` function:
```
dictionary = {key: value, key2: value2}
dictionary = dict([(key, value),(key2, value2)])
```

Keys can be a variety of data types, including numeric, strings, and tuples. However, they cannot be changeable objects, such as lists, or other dictionaries. Values, on the other hand, can be any data type.

Accessing the dictionary values are done using square brackets using the syntax:
```
dictionary[key] # returns the value associated with key
```

In [0]:
pokemon_types = {'bulbasaur':'grass', 'charmander':'fire', 'squirtle':'water'}
print(pokemon_types['bulbasaur'])

grass


You can add or change an element to a dictionary using the following syntax:
```
dictionary[key] = value
```

In [0]:
pokemon_types['bulbasaur'] = 'grass/poison' #bulbasaur is actually dual typed, so we'll change its entry
pokemon_types['ivysaur'] = 'grass/poison' #let's add an evolution
print(pokemon_types)

{'bulbasaur': 'grass/poison', 'charmander': 'fire', 'squirtle': 'water', 'ivysaur': 'grass/poison'}


You can get a list of all of the keys to a dictionary using the `.keys()` function, similarly with the `.values()` function.

In [0]:
print(pokemon_types.keys())
print(pokemon_types.values())

dict_keys(['bulbasaur', 'charmander', 'squirtle', 'ivysaur'])
dict_values(['grass/poison', 'fire', 'water', 'grass/poison'])


You can use the function `.items()` to get a list of `(key, value)` tuples. This is often useful for looping

In [0]:
for k, v in pokemon_types.items():
  print('the type of {} is {}'.format(k,v))

the type of bulbasaur is grass/poison
the type of charmander is fire
the type of squirtle is water
the type of ivysaur is grass/poison


# Numpy
Numpy is a package for python which provides various tools to make math and numerical computation much easier. One of the key components is the numpy array, which enables matrices.

The content in this section is adapted from the Python Data Science Handbook, which is [freely available online](https://github.com/jakevdp/PythonDataScienceHandbook)

## numpy arrays
numpy arrays provide the ability to create matrices, which are essentially 2-dimensional lists. (They can also be used to create even higher-dimensional arrays: tensors, etc)
Unlike python lists, numpy arrays must all have the same data type (e.g. numeric, string). 

Arrays can be created from python lists:

In [0]:
print('a vector can be created from a list {}'.format(np.array([1, 4, 2, 5, 3])))
print('a matrix can be created from a list of lists:\n {}'.format(np.array([[1,1,1],[2,2,2],[3,3,3]]))) #\n is the newline character and makes the following text appear on the next line

a vector can be created from a list [1 4 2 5 3]
a matrix can be created from a list of lists:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]


There are also a bunch of built-in functions for generating arrays. 

In [0]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [0]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.79095346, 0.91561782, 0.13141375],
       [0.42664129, 0.55811718, 0.99544769],
       [0.20889699, 0.89831355, 0.73445433]])

In [0]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.80769217, -0.45471375,  0.07699694],
       [-1.20444781,  1.21756476, -0.5580331 ],
       [-2.88759407,  0.49624041,  0.87205832]])

In [0]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 5, 6],
       [0, 9, 1],
       [7, 1, 1]])

In [0]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

## Array attributes

In [0]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print('x1=',x1)
print('x2=',x2)
print('x3=',x3)

x1= [1 2 2 8 3 5]
x2= [[9 2 0 3]
 [4 8 1 3]
 [2 1 1 2]]
x3= [[[1 8 2 4 9]
  [5 8 9 1 4]
  [2 9 9 4 9]
  [8 0 3 9 7]]

 [[9 9 3 3 2]
  [2 7 9 4 5]
  [3 6 3 2 9]
  [0 8 0 1 8]]

 [[3 6 3 8 2]
  [2 7 8 8 9]
  [8 5 3 9 6]
  [2 9 3 0 3]]]


In [0]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


## Array Indexing
You can index arrays much in the same way that you can index python lists

One-dimensional arrays function just like lists

In [0]:
print('x1 is', x1)
print('first entry is', x1[0]) # first entry of the array
print('second and third entries are', x1[[1,2]])
print('first three entries are', x1[:3]) # slice the array
print('a second set of colons in the slice allow you to set the interval:', x1[::2]) # every other element of x1
print('you can reverse the order using a negative interval:', x1[3::-1]) # count backwards from entry at index 3 to the beginning

x1 is [1 2 2 8 3 5]
first entry is 1
second and third entries are [2 2]
first three entries are [1 2 2]
a second set of colons in the slice allow you to set the interval: [1 2 3]
you can reverse the order using a negative interval: [8 2 2 1]


Multi-dimensional arrays are indexed using a tuple of indices. The indices for a 2d array are ordered as `(row_idx, col_idx)`

In [0]:
print(x2)
print('the element in the second row, third column is: ', x2[(1,2)])

[[3 5 2 1]
 [7 5 3 6]
 [3 3 3 5]]
the element in the second row, third column is:  3


You can slice multidimensional arrays as well!

If you change the value of an entry in a slice, you change the value in the original object. This is what's known as a "view" of an array. Slices do not return an independent object, but instead can be thought of as just a reference to a subset of elements in the original object.

However, if you do not want this behavior, you can avoid it by making a copy using the `.copy()` function.

In [0]:
print('x2 is originally: \n', x2)
slice_of_x2 = x2[1:,2:] # slices the 2nd row to the end, and 3rd column to the end
copied_slice_of_x2 = x2[1:,2:].copy() # note that slices provide a direct view of the original object, if you want an independent copy, use the .copy()
print('slice_of_x2 is:\n',slice_of_x2)
print('copied_slice_of_x2 is: \n', copied_slice_of_x2)

x2 is originally: 
 [[3 5 2 1]
 [7 5 3 6]
 [3 3 3 5]]
slice_of_x2 is:
 [[3 6]
 [3 5]]
copied_slice_of_x2 is: 
 [[3 6]
 [3 5]]


In [0]:
# let's change the value of slice_of_x2
slice_of_x2[0,0] = 99 # we changed the value of top left element to 99; this corresponds to the element in the 2nd row, 3rd column of x2
print('now x2 is: \n', x2)
print('slice_of_x2 is:\n',slice_of_x2)
print('and copied_slice_of_x2 is:\n',copied_slice_of_x2)

now x2 is: 
 [[ 3  5  2  1]
 [ 7  5 99  6]
 [ 3  3  3  5]]
slice_of_x2 is:
 [[99  6]
 [ 3  5]]
and copied_slice_of_x2 is:
 [[3 6]
 [3 5]]


In [0]:
# If you change the value of a copy, it does not affect the original object
copied_slice_of_x2[0,0] = -50
print('copied_slice_of_x2 is: \n', copied_slice_of_x2)
print('x2 is unchanged by this operation:\n', x2)

copied_slice_of_x2 is: 
 [[-50   6]
 [  3   5]]
x2 is unchanged by this operation:
 [[ 3  5  2  1]
 [ 7  5 99  6]
 [ 3  3  3  5]]


## Reshaping
You can reshape an array using the `.reshape()` function

In [0]:
print('np.arange(12):',np.arange(12))
reshaped = np.arange(12).reshape(3,4)
print('reshaped into a 3x4 array: \n',reshaped)


np.arange(12): [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped into a 3x4 array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


You can combine and split arrays in numpy. However, we won't be going too much in depth with that. Check out [this tutorial](https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.02-The-Basics-Of-NumPy-Arrays.ipynb) for more info in that realm.

## Boolean arrays and masking
Boolean data represents True/False values, which can also be expressed as 1 or 0 respectively.

You can compute boolean operations on arrays in numpy

In [0]:
even_entries_bool = np.mod(reshaped,2)==0
print(even_entries_bool)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


You can then use those arrays to select the entries which match that criteria

In [0]:
reshaped[even_entries_bool]

array([ 0,  2,  4,  6,  8, 10])

### Exercise
Using the `is_prime()` function we previously wrote, write a function which takes a numpy array and returns a boolean array of the prime entries with the same shape as the input array

In [0]:
def is_prime_array(input_array):
  """
  returns a boolean array of the same shape as input_array
  with True if the element in the same position of input_array is prime 
  and False otherwise
  
  example: 
  x = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
  is_prime_array(x)
  should return
  [[False, False, True, True],
   [False, True, False, True],
   [False, False, False, True]]
  """
  # fill in with your code
  sizer = input_array.size
  print(sizer)
  array = np.zeros(sizer, dtype=bool)
  counter=0
  
  #prime_entries_bool = np.copy(input_array).
  for x in np.nditer(input_array):
    #print (x)
    if is_prime(x)== True:
      array[counter] = True
      counter+=1
    else:
      array[counter]= False
      counter+=1   
   
      
      
        
  array = array.reshape(input_array.shape)
  print(input_array)
  print(array)
  return array

In [0]:
is_prime_array(x3)

60
[[[1 8 2 4 9]
  [5 8 9 1 4]
  [2 9 9 4 9]
  [8 0 3 9 7]]

 [[9 9 3 3 2]
  [2 7 9 4 5]
  [3 6 3 2 9]
  [0 8 0 1 8]]

 [[3 6 3 8 2]
  [2 7 8 8 9]
  [8 5 3 9 6]
  [2 9 3 0 3]]]
[[[False False  True False False]
  [ True False False False False]
  [ True False False False False]
  [False False  True False  True]]

 [[False False  True  True  True]
  [ True  True False False  True]
  [ True False  True  True False]
  [False False False False False]]

 [[ True False  True False  True]
  [ True  True False False False]
  [False  True  True False False]
  [ True False  True False  True]]]


array([[[False, False,  True, False, False],
        [ True, False, False, False, False],
        [ True, False, False, False, False],
        [False, False,  True, False,  True]],

       [[False, False,  True,  True,  True],
        [ True,  True, False, False,  True],
        [ True, False,  True,  True, False],
        [False, False, False, False, False]],

       [[ True, False,  True, False,  True],
        [ True,  True, False, False, False],
        [False,  True,  True, False, False],
        [ True, False,  True, False,  True]]])

## Random functions
You'll often need random numbers in programming. For example: taking a random sample of data, simulating a coin flip/dice roll, and generating simulated data.

Numpy has a bunch of built-in random functions for this purpose. These functions are accessible in the `np.random` submodule

In [0]:
np.random.rand(2,3,4) # generates uniform random numbers between 0,1
# arguments of rand(a,b,c,d,...) determine the dimensions of the array
# in this case, we created a 2x3x4 3d array

array([[[0.97366113, 0.39019088, 0.37294465, 0.53416539],
        [0.86044884, 0.45700072, 0.46351811, 0.09171856],
        [0.81231621, 0.32456726, 0.84509228, 0.79129362]],

       [[0.25338937, 0.4491814 , 0.30771055, 0.30319296],
        [0.11869015, 0.29820029, 0.79733477, 0.62599133],
        [0.51338586, 0.22555279, 0.34591956, 0.38343785]]])

In [0]:
np.random.rand(10) # we can use this just to get a list of 10 random numbers from [0,1)

array([0.72727749, 0.55207869, 0.11572649, 0.57004251, 0.8916866 ,
       0.09567433, 0.27384214, 0.43740519, 0.76278691, 0.71091504])

In [0]:
np.random.randn(5) # randn is the standard normal distribution (gaussian)
# by default, it has mean=0 and variance=1

array([-0.24870937,  0.85588667,  0.91015428,  1.19461364,  1.15368334])

In [0]:
# you can scale the gaussian to have different mean and variance
# for example, to have mean=3 and variance=2
def scaled_randn(mean, var, n_samples):
  return mean + np.random.randn(n_samples)*var
scaled_randn(3,2,100)

array([ 1.84145868,  4.04694305,  3.71691567,  7.37976424,  3.49375706,
        4.08184224,  2.81343312,  1.62807008,  1.1575889 ,  3.25770321,
        3.81804985,  4.09787886,  5.02316319,  2.13359593,  2.46534311,
        3.86314102,  0.63860894,  3.05650094, -2.07986432,  7.30619736,
        2.05951853,  2.51254776,  2.33521345,  5.12537685,  3.90446943,
        4.58958278,  4.0630235 ,  2.34101574,  2.54503972,  2.9911283 ,
        2.09647087,  4.82835551,  4.20087608,  3.65991316, -0.23308466,
        1.49993187,  5.70809354,  4.14736301,  1.01650588,  8.5758993 ,
        2.29655866,  6.78439949,  1.76709913,  1.84986863,  1.51398393,
        4.58646941,  3.92420091,  3.20413495, -1.33023811,  6.89989825,
        0.5804412 ,  1.13602846,  2.02306794,  3.02927404,  2.10577745,
        0.67994556,  3.47151461, -1.72333221,  1.70569643,  3.11511929,
        7.21009824,  5.65923641,  5.38849819,  7.41939055,  2.28599884,
        3.17630526, -0.58779176,  0.85475517,  2.40830428,  2.96

In [0]:
# randint gives random integers. Arguments are (low, high, size)
# randint operates on the interval [low,high) (high is not included)
np.random.randint(1,10,20)

array([4, 7, 5, 6, 4, 1, 1, 6, 3, 1, 7, 8, 1, 1, 4, 3, 2, 1, 8, 6])

In [0]:
# if you want it to be inclusive, then you should call randint(low,high+1,size)
np.random.randint(1,11,20)

array([ 9,  4,  2,  8, 10,  3, 10, 10,  7,  9,  2,  6,  9,  3,  4,  7,  4,
        6,  7, 10])

In [0]:
#randint is useful to generate a random sample with replacement of a collection
letters = np.array(['a','b','c','d','e','f'])
rand_idx = np.random.randint(0,len(letters),10) #len(letters) is the length of letters
letters[rand_idx]

array(['d', 'f', 'c', 'e', 'd', 'f', 'b', 'a', 'e', 'd'], dtype='<U1')

In [0]:
# if you don't want sampling with replacement, you can use permutation
np.random.permutation(letters)

array(['e', 'a', 'f', 'b', 'd', 'c'], dtype='<U1')

In [0]:
# another way to do sampling is with the choice(x[, size, replace, p]) function
print(np.random.choice(letters)) # x is the only required argument, will just return one random entry


b
['c' 'e' 'a' 'b' 'c' 'a' 'e' 'f' 'd' 'b']
[['c' 'e' 'e']
 ['e' 'e' 'b']]
[['e' 'f' 'c']
 ['d' 'b' 'a']]


In [0]:
print(np.random.choice(letters, 10)) # size lets you specify how many to sample


['b' 'e' 'e' 'c' 'e' 'c' 'e' 'b' 'b' 'c']


In [0]:
print(np.random.choice(letters, [2,3])) # can be multi dimensional

[['d' 'b' 'e']
 ['b' 'b' 'c']]


In [0]:
print(np.random.choice(letters, [2,3], False)) # whether to sample with replacement (default True)

[['b' 'a' 'f']
 ['e' 'd' 'c']]


In [0]:
# by default, choice() uses a uniform random probability (i.e. fair dice)
# sometimes you want to weight certain outcomes to be more likely
# p allows you to do that by specifying the probabilities of each outcome
# let's make 'a' be much more likely than the others
print(np.random.choice(letters, 100, True, [0.75,0.05,0.05,0.05,0.05,0.05]))

['a' 'c' 'a' 'c' 'd' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'd' 'f' 'a' 'a' 'c' 'a'
 'a' 'a' 'a' 'b' 'a' 'a' 'a' 'a' 'c' 'a' 'd' 'a' 'a' 'a' 'a' 'a' 'a' 'd'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'e' 'a' 'a' 'a' 'a' 'a' 'a' 'f' 'b' 'a'
 'c' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'e' 'a' 'c' 'a' 'a' 'f' 'c' 'a' 'a' 'a'
 'e' 'a' 'a' 'a' 'a' 'c' 'a' 'a' 'a' 'a' 'e' 'f' 'a' 'a' 'a' 'a' 'a' 'a'
 'd' 'a' 'a' 'a' 'b' 'a' 'd' 'a' 'e' 'f']
